// <auto-generated />
using System;
using Hermod.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hermod.Data.Migrations
{
    [DbContext(typeof(HermodContext))]
    partial class HermodContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Hermod.Data.Entities.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowSharing")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DiscordGuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DiscordPostChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordGuildId")
                        .IsUnique()
                        .HasFilter("DiscordGuildId IS NOT NULL");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BgStatsPlayUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BggGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPlayFileJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rounds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BgStatsPlayUuid");

                    b.HasIndex("DatePlayed");

                    b.HasIndex("GroupId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayPlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BgStatsPlayerUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CalculatedScore")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("MappedUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NewPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Score")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StartPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Winner")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MappedUserId");

                    b.HasIndex("PlayId");

                    b.ToTable("PlayPlayers");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayerMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BgStatsPlayerUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MappedUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MappedUserId");

                    b.HasIndex("OwnerUserId", "BgStatsPlayerUuid")
                        .IsUnique();

                    b.ToTable("PlayerMappings");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BggId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BggUsername")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SubscribeToPlays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique()
                        .HasFilter("DiscordId IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UserGroupEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayEntity", b =>
                {
                    b.HasOne("Hermod.Data.Entities.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Hermod.Data.Entities.UserEntity", "UploadedBy")
                        .WithMany("UploadedPlays")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayPlayerEntity", b =>
                {
                    b.HasOne("Hermod.Data.Entities.UserEntity", "MappedUser")
                        .WithMany()
                        .HasForeignKey("MappedUserId");

                    b.HasOne("Hermod.Data.Entities.PlayEntity", "Play")
                        .WithMany("Players")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MappedUser");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayerMappingEntity", b =>
                {
                    b.HasOne("Hermod.Data.Entities.UserEntity", "MappedUser")
                        .WithMany()
                        .HasForeignKey("MappedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hermod.Data.Entities.UserEntity", "Owner")
                        .WithMany("PlayerMappings")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MappedUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UserGroupEntity", b =>
                {
                    b.HasOne("Hermod.Data.Entities.GroupEntity", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hermod.Data.Entities.UserEntity", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hermod.Data.Entities.GroupEntity", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayEntity", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("PlayerMappings");

                    b.Navigation("UploadedPlays");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
