// <auto-generated />
using System;
using Hermod.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hermod.Data.Migrations
{
    [DbContext(typeof(HermodContext))]
    partial class HermodContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hermod.Data.Entities.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowSharing")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BgStatsPlayUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("BggGameId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GameThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LocationName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Rounds")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UploadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BgStatsPlayUuid");

                    b.HasIndex("DatePlayed");

                    b.HasIndex("GroupId");

                    b.HasIndex("UploadId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayPlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BgStatsPlayerUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("CalculatedScore")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("MappedUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NewPlayer")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Score")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("StartPlayer")
                        .HasColumnType("boolean");

                    b.Property<string>("Team")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Winner")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MappedUserId");

                    b.HasIndex("PlayId");

                    b.ToTable("PlayPlayers");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayerMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BgStatsPlayerUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("MappedUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MappedUserId");

                    b.HasIndex("BgStatsPlayerUuid", "MappedUserId")
                        .IsUnique();

                    b.ToTable("PlayerMappings");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UploadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("FileBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadedById");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UserGroupEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("BggId")
                        .HasColumnType("integer");

                    b.Property<string>("BggUsername")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("SubscribeToPlays")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayEntity", b =>
                {
                    b.HasOne("Hermod.Data.Entities.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Hermod.Data.Entities.UploadEntity", "Upload")
                        .WithMany("Plays")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hermod.Data.Entities.UserProfileEntity", "UploadedBy")
                        .WithMany("UploadedPlays")
                        .HasForeignKey("UploadedById");

                    b.Navigation("Group");

                    b.Navigation("Upload");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayPlayerEntity", b =>
                {
                    b.HasOne("Hermod.Data.Entities.UserProfileEntity", "MappedUser")
                        .WithMany()
                        .HasForeignKey("MappedUserId");

                    b.HasOne("Hermod.Data.Entities.PlayEntity", "Play")
                        .WithMany("Players")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MappedUser");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayerMappingEntity", b =>
                {
                    b.HasOne("Hermod.Data.Entities.UserProfileEntity", "MappedUser")
                        .WithMany("PlayerMappings")
                        .HasForeignKey("MappedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MappedUser");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UploadEntity", b =>
                {
                    b.HasOne("Hermod.Data.Entities.UserProfileEntity", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UserGroupEntity", b =>
                {
                    b.HasOne("Hermod.Data.Entities.GroupEntity", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hermod.Data.Entities.UserProfileEntity", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hermod.Data.Entities.GroupEntity", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Hermod.Data.Entities.PlayEntity", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UploadEntity", b =>
                {
                    b.Navigation("Plays");
                });

            modelBuilder.Entity("Hermod.Data.Entities.UserProfileEntity", b =>
                {
                    b.Navigation("PlayerMappings");

                    b.Navigation("UploadedPlays");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
