<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.1.1" />
    <PackageReference Include="AspNet.Security.OAuth.Discord" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" PrivateAssets="all" />
    <PackageReference Include="WolverineFx.Http" Version="5.*" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="5.*" />
    <PackageReference Include="WolverineFx.Nats" Version="5.*" />
    <PackageReference Include="WolverineFx.Postgresql" Version="5.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hermod.ServiceDefaults\Hermod.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Hermod.Data\Hermod.Data.csproj" />
    <ProjectReference Include="..\Hermod.BGStats\Hermod.BGStats.csproj" />
    <ProjectReference Include="..\Hermod.Messages\Hermod.Messages.csproj" />
  </ItemGroup>

</Project>
