<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Riok.Mapperly" Version="4.*" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hermod.BGStats\Hermod.BGStats.csproj" />
    <ProjectReference Include="..\Hermod.Data\Hermod.Data.csproj" />
  </ItemGroup>

</Project>
